enum ErrorCode {
  UNKNOWN = 'E000',
  EMAIL_ALREADY_IN_USE = 'E001',
  VALIDATION_ERROR = 'E002',
  USER_DOES_NOT_EXIST = 'E003',
  ROLE_UNAUTHORIZED = 'E004',
  INVALID_CREDENTIALS = 'E005',
  PARAMETER_REQUIRES_AUTHENTICATION = 'E006',
  UNAUTHENTICATED = 'E007',
}

export default ErrorCode
