enum ErrorCode {
  UNKNOWN = 'E000',
  EMAIL_ALREADY_IN_USE = 'E001',
  VALIDATION_ERROR = 'E002',
  USER_DOES_NOT_EXIST = 'E003',
  ROLE_UNAUTHORIZED = 'E004',
  INVALID_CREDENTIALS = 'E005',
  PARAMETER_REQUIRES_AUTHENTICATION = 'E006',
  USER_ALREADY_HAS_THIS_ROLE = 'E007',
  ROOT_CREDENTIALS_NOT_DEFINED = 'E008',
  ROOT_CREDENTIALS_CONFLICT = 'E009',
  CHAMPIONSHIP_NOT_FOUND = 'E010',
  CHAMPIONSHIP_SLUG_ALREADY_IN_USE = 'E011',
  REGION_NOT_FOUND = 'E012',
  REGION_SLUG_ALREADY_IN_USE = 'E013',
  TEAM_NOT_FOUND = 'E014',
  TEAM_SLUG_ALREADY_IN_USE = 'E015',
  MATCH_NOT_FOUND = 'E016',
}

export default ErrorCode
